"""
API Template - Templates for API client code
"""

REQUESTS_TEMPLATE = '''# API Client - Requests Version
# Generated by Universal API Tester

import requests
import json
import time
from typing import Dict, Any, Optional

class APIClient:
    """API Client for {service_name}"""
    
    def __init__(self, base_url: str = "{base_url}"):
        self.base_url = base_url
        self.session = requests.Session()
        
        # Default headers
        self.session.headers.update({{
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'Accept': 'application/json, text/plain, */*',
            'Content-Type': 'application/json'
        }})
        
        # Request settings
        self.timeout = 30
        self.retry_attempts = 3
        self.retry_delay = 1

    def _make_request(self, method: str, endpoint: str, **kwargs) -> Dict[str, Any]:
        """Make HTTP request with error handling"""
        url = f"{{self.base_url}}{{endpoint}}"
        
        for attempt in range(self.retry_attempts):
            try:
                response = self.session.request(
                    method, 
                    url, 
                    timeout=self.timeout,
                    **kwargs
                )
                
                response.raise_for_status()
                
                # Parse response
                content_type = response.headers.get('content-type', '')
                if 'application/json' in content_type:
                    data = response.json()
                else:
                    data = response.text
                
                return {{
                    'success': True,
                    'status_code': response.status_code,
                    'data': data,
                    'headers': dict(response.headers)
                }}
                
            except requests.exceptions.RequestException as e:
                if attempt == self.retry_attempts - 1:
                    return {{
                        'success': False,
                        'error': str(e),
                        'status_code': getattr(e.response, 'status_code', None) if hasattr(e, 'response') else None
                    }}
                time.sleep(self.retry_delay)

{api_methods}

# Usage example
if __name__ == '__main__':
    client = APIClient()
    
    # Example API calls
    print("API Client initialized")
    # result = client.get_data()
    # print(f"Result: {{result}}")
'''

AIOHTTP_TEMPLATE = '''# API Client - aiohttp Version
# Generated by Universal API Tester

import aiohttp
import asyncio
import json
import time
from typing import Dict, Any, Optional

class AsyncAPIClient:
    """Async API Client for {service_name}"""
    
    def __init__(self, base_url: str = "{base_url}"):
        self.base_url = base_url
        self.session = None
        self.default_headers = {{
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'Accept': 'application/json, text/plain, */*',
            'Content-Type': 'application/json'
        }}
        self.timeout = aiohttp.ClientTimeout(total=30)

    async def __aenter__(self):
        self.session = aiohttp.ClientSession(
            headers=self.default_headers,
            timeout=self.timeout
        )
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        await self.session.close()

    async def _make_request(self, method: str, endpoint: str, **kwargs) -> Dict[str, Any]:
        """Make async HTTP request with error handling"""
        url = f"{{self.base_url}}{{endpoint}}"
        
        try:
            async with self.session.request(method, url, **kwargs) as response:
                response.raise_for_status()
                
                content_type = response.headers.get('content-type', '')
                if 'application/json' in content_type:
                    data = await response.json()
                else:
                    data = await response.text()
                
                return {{
                    'success': True,
                    'status_code': response.status,
                    'data': data,
                    'headers': dict(response.headers)
                }}
                
        except aiohttp.ClientError as e:
            return {{
                'success': False,
                'error': str(e)
            }}

{api_methods}

# Usage example
async def main():
    async with AsyncAPIClient() as client:
        print("Async API Client initialized")
        # Example API calls
        # result = await client.get_data()
        # print(f"Result: {{result}}")

if __name__ == '__main__':
    asyncio.run(main())
'''

METHOD_TEMPLATE = '''
    def {method_name}(self{parameters}) -> Dict[str, Any]:
        """
        {description}
        
        Endpoint: {endpoint}
        Method: {method}
        """
        return self._make_request("{method}", "{endpoint}")

'''

ASYNC_METHOD_TEMPLATE = '''
    async def {method_name}(self{parameters}) -> Dict[str, Any]:
        """
        {description}
        
        Endpoint: {endpoint}
        Method: {method}
        """
        return await self._make_request("{method}", "{endpoint}")

'''

CURL_TEMPLATE = '''# cURL Commands for {service_name}
# Generated by Universal API Tester

{curl_commands}

# Usage:
# Copy and paste these commands in terminal
# Or use in scripts with $(curl ...)
'''

SINGLE_CURL_TEMPLATE = '''# {description}
curl -X {method} \\
{headers}{data}
  "{url}"

'''
