"""
Bot Template - Template for generating bot code
"""

BOT_TEMPLATE = '''# Auto-generated Bot Code
# Generated by Universal API Tester
# Date: {generation_date}

import requests
import json
import time
import logging
from typing import Dict, Any, Optional, List

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class {bot_class_name}:
    """
    Auto-generated API Bot
    Total APIs: {total_apis}
    """
    
    def __init__(self, base_url: str = None):
        self.session = requests.Session()
        self.base_url = base_url or "{base_url}"
        
        # Configure default headers
        self.session.headers.update({{
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'Accept': 'application/json, text/plain, */*',
            'Accept-Language': 'en-US,en;q=0.9',
            'Content-Type': 'application/json'
        }})
        
        logger.info("Bot initialized")

    def login(self, username: str, password: str) -> bool:
        """
        Login to the system
        Modify this method based on your authentication requirements
        """
        try:
            # Example login implementation
            login_data = {{
                'username': username,
                'password': password
            }}
            
            response = self.session.post(
                f"{{self.base_url}}/login",
                json=login_data,
                timeout=30
            )
            
            if response.status_code == 200:
                logger.info("Login successful")
                return True
            else:
                logger.error(f"Login failed: {{response.status_code}}")
                return False
                
        except Exception as e:
            logger.error(f"Login error: {{e}}")
            return False

{api_methods}

    def make_request(self, method: str, endpoint: str, **kwargs) -> Dict[str, Any]:
        """
        Generic request method
        """
        try:
            url = f"{{self.base_url}}{{endpoint}}"
            
            # Ensure proper headers
            headers = kwargs.get('headers', {{}})
            if 'Content-Type' not in headers:
                headers['Content-Type'] = 'application/json'
            kwargs['headers'] = headers
            
            response = self.session.request(method, url, **kwargs)
            response.raise_for_status()
            
            return {{
                'success': True,
                'status_code': response.status_code,
                'data': response.json() if response.headers.get('content-type') == 'application/json' else response.text,
                'headers': dict(response.headers)
            }}
            
        except requests.RequestException as e:
            logger.error(f"Request failed: {{e}}")
            return {{
                'success': False,
                'error': str(e),
                'status_code': getattr(e.response, 'status_code', None) if hasattr(e, 'response') else None
            }}

# Example usage
if __name__ == '__main__':
    # Initialize bot
    bot = {bot_class_name}()
    
    # Example: Login (modify credentials)
    # if bot.login("your_username", "your_password"):
    #     print("Login successful")
    
    # Example: Call API methods
    # result = bot.example_api_method()
    # print(f"API Result: {{result}}")
    
    print("Bot ready - Modify the code above for your specific needs")
'''

API_METHOD_TEMPLATE = '''
    def {method_name}(self, **kwargs) -> Dict[str, Any]:
        """
        {api_description}
        
        URL: {api_url}
        Method: {http_method}
        """
        endpoint = "{endpoint}"
        return self.make_request("{http_method}", endpoint, **kwargs)
'''

AIOHTTP_TEMPLATE = '''# Auto-generated Async Bot Code
# Generated by Universal API Tester
# Date: {generation_date}

import aiohttp
import asyncio
import json
import time
import logging
from typing import Dict, Any, Optional, List

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class Async{bot_class_name}:
    """
    Auto-generated Async API Bot
    Total APIs: {total_apis}
    """
    
    def __init__(self, base_url: str = None):
        self.base_url = base_url or "{base_url}"
        self.session = None
        self.default_headers = {{
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'Accept': 'application/json, text/plain, */*',
            'Accept-Language': 'en-US,en;q=0.9',
            'Content-Type': 'application/json'
        }}

    async def __aenter__(self):
        self.session = aiohttp.ClientSession(headers=self.default_headers)
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        await self.session.close()

    async def login(self, username: str, password: str) -> bool:
        """
        Login to the system
        """
        try:
            login_data = {{
                'username': username,
                'password': password
            }}
            
            async with self.session.post(
                f"{{self.base_url}}/login",
                json=login_data,
                timeout=aiohttp.ClientTimeout(total=30)
            ) as response:
                if response.status == 200:
                    logger.info("Login successful")
                    return True
                else:
                    logger.error(f"Login failed: {{response.status}}")
                    return False
                    
        except Exception as e:
            logger.error(f"Login error: {{e}}")
            return False

{api_methods}

    async def make_request(self, method: str, endpoint: str, **kwargs) -> Dict[str, Any]:
        """
        Generic async request method
        """
        try:
            url = f"{{self.base_url}}{{endpoint}}"
            
            async with self.session.request(method, url, **kwargs) as response:
                response.raise_for_status()
                
                content_type = response.headers.get('content-type', '')
                if 'application/json' in content_type:
                    data = await response.json()
                else:
                    data = await response.text()
                
                return {{
                    'success': True,
                    'status_code': response.status,
                    'data': data,
                    'headers': dict(response.headers)
                }}
                
        except aiohttp.ClientError as e:
            logger.error(f"Request failed: {{e}}")
            return {{
                'success': False,
                'error': str(e)
            }}

# Example usage
async def main():
    async with Async{bot_class_name}() as bot:
        # Example: Login
        # if await bot.login("your_username", "your_password"):
        #     print("Login successful")
        
        # Example: Call API methods
        # result = await bot.example_api_method()
        # print(f"API Result: {{result}}")
        
        print("Async bot ready - Modify the code above for your specific needs")

if __name__ == '__main__':
    asyncio.run(main())
'''

ASYNC_API_METHOD_TEMPLATE = '''
    async def {method_name}(self, **kwargs) -> Dict[str, Any]:
        """
        {api_description}
        
        URL: {api_url}
        Method: {http_method}
        """
        endpoint = "{endpoint}"
        return await self.make_request("{http_method}", endpoint, **kwargs)
'''
